### ISSUE TITLE
[Mac High Sierra] /usr/bin/python instead of /usr/bin/python2 in ./waf file

### ISSUE THREAD

**Issue by onehr** [FujiZ/ns-3#11]
By default, in macOS the python binary locates in /usr/bin/python (version 2), so i think in macOS, the waf file should run by /usr/bin/python instead of /usr/bin/python2

**Comment by FujiZ** [comment]
Hey onehr, thanks for your feedback.
By default, the python path in ns-3 is '/usr/bin/env python'. Since I'm using ArchLinux and its default python version is 3.6, I have to change it to /usr/bin/python2 to make my life easier.
Now my work on this repo has finished, so I think its the time to change it back to the default setting. I have pushed a commit to fix this problem using `sed -i 's|/usr/bin/python2|/usr/bin/env python|g'`, so just enjoy it. :)
