### ISSUE TITLE
Missing "dcn" directory in last commit.

### ISSUE THREAD

**Issue by lanhao34** [FujiZ/ns-3#7]
Hello.
I have cloned your repo for last commit at Apr 9, 2017, but i found there is no "dcn" directory in the "src" directory and the error occurred while compiling.
"../scratch/dctcp-convergence-test.cc:8:28: fatal error: ns3/dcn-module.h: No such file or directory"
I fixed this problem by copy an "dcn" directory from previous commit. I think its just a mistake and you will fix it soon. :)

**Comment by FujiZ** [comment]
Thanks for your feedback.
The codes in dcn directory were part of our lab project. I removed them in the latest commit since they were not related to this repo. But I forgot to remove the header included in several scratch.
The latest commit I just pushed fixed this problem as well as several bugs in previous commit.
