### ISSUE TITLE
some question about D2TCP DecreaseWindow(）

### ISSUE THREAD

**Issue by hdtjiang** [FujiZ/ns-3#9]
hello，
I have found that you set the Tc as B*m_rtt->GetEstimate()->GetSeconds()/(3.0*m_tcb->m_cWnd()->Get()/4.0);
and in D2TCP,the Tc is B/(3W/4);
so I think the EstimatedRTT is not needed  and the m_cWnd() need to change to  Window();
thanks

**Comment by FujiZ** [comment]
Hi jiang,
According to the original paper, the result of Tc is B/(3W/4). 
However, as you can see, if we adopt this equation, the dimension of Tc and D is mismatched, thus makes it incomparable between Tc and D.
Since we send a window of data in roughly one RTT, we can take RTT estimation into consideration. Another repo [i-maravic/ns-3](https://github.com/i-maravic/ns-3) share the same implementation.

**Comment by hdtjiang** [comment]
Thanks for your answer.And i have got it.
